# Protege a aplicação Java, aceitando conexões de entrada apenas de dentro
# do cluster (mesmo bloco de rede dos pods).
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-security-policy
  namespace: tech-challenge
spec:
  podSelector:
    matchLabels:
      app: spring-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.0.0/8
      ports:
        - protocol: TCP
          port: 8080
